- ======================================================
-- GLOBAL SUPERSTORE SNOWFLAKE ETL SETUP
-- ======================================================

-- 1️⃣ USE THE CORRECT WAREHOUSE
USE WAREHOUSE SUPERSTORE_WH;

-- 2️⃣ CREATE DATABASE & SCHEMAS
CREATE OR REPLACE DATABASE GLOBAL_SUPERSTORE_DW;
USE DATABASE GLOBAL_SUPERSTORE_DW;

CREATE OR REPLACE SCHEMA RAW_STAGE;
CREATE OR REPLACE SCHEMA DW;

CREATE OR REPLACE SCHEMA TRANSFORM;

-- 3️⃣ VERIFY CONTEXT
SELECT CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();


