-- ======================================================
-- DIMENSION CREATION SCRIPT
-- ======================================================
USE WAREHOUSE SUPERSTORE_WH;
USE DATABASE GLOBAL_SUPERSTORE_DW;
USE SCHEMA TRANSFORM;



-- DimDate
CREATE OR REPLACE TABLE DIM_DATE AS
SELECT DISTINCT
    TO_NUMBER(TO_CHAR(ORDER_DATE, 'YYYYMMDD')) AS DATE_KEY,
    ORDER_DATE AS FULL_DATE,
    YEAR(ORDER_DATE) AS YEAR,
    MONTH(ORDER_DATE) AS MONTH,
    QUARTER(ORDER_DATE) AS QUARTER,
    DAY(ORDER_DATE) AS DAY,
    DAYNAME(ORDER_DATE) AS DAY_OF_WEEK
FROM RAW_STAGE.STG_GLOBAL_SUPERSTORE
UNION
SELECT DISTINCT
    TO_NUMBER(TO_CHAR(SHIP_DATE, 'YYYYMMDD')) AS DATE_KEY,
    SHIP_DATE AS FULL_DATE,
    YEAR(SHIP_DATE) AS YEAR,
    MONTH(SHIP_DATE) AS MONTH,
    QUARTER(SHIP_DATE) AS QUARTER,
    DAY(SHIP_DATE) AS DAY,
    DAYNAME(SHIP_DATE) AS DAY_OF_WEEK
FROM RAW_STAGE.STG_GLOBAL_SUPERSTORE;

-- DimCustomer
CREATE OR REPLACE TABLE DIM_CUSTOMER AS
SELECT DISTINCT
    CUSTOMER_ID AS CUSTOMER_KEY,
    CUSTOMER_NAME,
    SEGMENT
FROM RAW_STAGE.STG_GLOBAL_SUPERSTORE;

-- DimProduct
CREATE OR REPLACE TABLE DIM_PRODUCT AS
SELECT DISTINCT
    PRODUCT_ID AS PRODUCT_KEY,
    PRODUCT_NAME,
    CATEGORY,
    SUB_CATEGORY
FROM RAW_STAGE.STG_GLOBAL_SUPERSTORE;

-- DimGeography
CREATE OR REPLACE TABLE DIM_GEOGRAPHY AS
SELECT DISTINCT
    MD5(CONCAT(COUNTRY, STATE, CITY, REGION)) AS GEO_KEY,
    COUNTRY,
    STATE,
    CITY,
    REGION
FROM RAW_STAGE.STG_GLOBAL_SUPERSTORE;

-- DimShipping
CREATE OR REPLACE TABLE DIM_SHIPPING AS
SELECT DISTINCT
    MD5(SHIP_MODE) AS SHIP_KEY,
    SHIP_MODE,
    CASE 
        WHEN SHIP_MODE ILIKE '%First%' THEN 'High Priority'
        WHEN SHIP_MODE ILIKE '%Second%' THEN 'Medium Priority'
        ELSE 'Standard Priority'
    END AS SHIP_PRIORITY
FROM RAW_STAGE.STG_GLOBAL_SUPERSTORE;