-- ======================================================
-- FACT TABLE CREATION
-- ======================================================
USE WAREHOUSE SUPERSTORE_WH;
USE DATABASE GLOBAL_SUPERSTORE_DW;
USE SCHEMA TRANSFORM;


-- FactSales
CREATE OR REPLACE TABLE FACT_SALES AS
SELECT
    TO_NUMBER(TO_CHAR(ORDER_DATE, 'YYYYMMDD')) AS ORDER_DATE_KEY,
    CUSTOMER_ID AS CUSTOMER_KEY,
    PRODUCT_ID AS PRODUCT_KEY,
    MD5(CONCAT(COUNTRY, STATE, CITY, REGION)) AS GEO_KEY,
    MD5(SHIP_MODE) AS SHIP_KEY,
    ORDER_ID,
    SALES AS SALES_AMOUNT,
    PROFIT AS PROFIT_AMOUNT,
    QUANTITY AS QUANTITY_SOLD,
    DISCOUNT AS DISCOUNT_PERCENT
FROM RAW_STAGE.STG_GLOBAL_SUPERSTORE;

-- FactShipping
CREATE OR REPLACE TABLE FACT_SHIPPING AS
SELECT
    TO_NUMBER(TO_CHAR(ORDER_DATE, 'YYYYMMDD')) AS ORDER_DATE_KEY,
    TO_NUMBER(TO_CHAR(SHIP_DATE, 'YYYYMMDD')) AS SHIP_DATE_KEY,
    CUSTOMER_ID AS CUSTOMER_KEY,
    PRODUCT_ID AS PRODUCT_KEY,
    MD5(CONCAT(COUNTRY, STATE, CITY, REGION)) AS GEO_KEY,
    MD5(SHIP_MODE) AS SHIP_KEY,
    ORDER_ID,
    DATEDIFF(DAY, ORDER_DATE, SHIP_DATE) AS DAYS_TO_SHIP,
    CASE WHEN DATEDIFF(DAY, ORDER_DATE, SHIP_DATE) > 5 THEN 'Late' ELSE 'OnTime' END AS LATE_FLAG,
    CASE 
        WHEN SHIP_MODE ILIKE '%First%' THEN 25
        WHEN SHIP_MODE ILIKE '%Second%' THEN 15
        ELSE 10
    END AS SHIPPING_COST
FROM RAW_STAGE.STG_GLOBAL_SUPERSTORE;

-- FactCustomerMonthly
CREATE OR REPLACE TABLE FACT_CUSTOMER_MONTHLY AS
SELECT
    TO_NUMBER(TO_CHAR(ORDER_DATE, 'YYYYMM')) AS MONTH_KEY,
    CUSTOMER_ID AS CUSTOMER_KEY,
    MD5(CONCAT(COUNTRY, STATE, CITY, REGION)) AS GEO_KEY,
    COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT,
    SUM(SALES) AS TOTAL_SALES,
    SUM(PROFIT) AS TOTAL_PROFIT,
    ROUND(AVG(SALES), 2) AS AVG_ORDER_VALUE,
    ROUND(SUM(PROFIT)/NULLIF(SUM(SALES),0),4) AS PROFIT_MARGIN_PCT
FROM RAW_STAGE.STG_GLOBAL_SUPERSTORE
GROUP BY 1,2,3;

-- FactProductMonthly
CREATE OR REPLACE TABLE FACT_PRODUCT_MONTHLY AS
SELECT
    TO_NUMBER(TO_CHAR(ORDER_DATE, 'YYYYMM')) AS MONTH_KEY,
    PRODUCT_ID AS PRODUCT_KEY,
    MD5(CONCAT(COUNTRY, STATE, CITY, REGION)) AS GEO_KEY,
    SUM(SALES) AS MONTHLY_SALES,
    SUM(PROFIT) AS MONTHLY_PROFIT,
    SUM(QUANTITY) AS MONTHLY_QUANTITY,
    ROUND(SUM(PROFIT)/NULLIF(SUM(SALES),0),4) AS PROFIT_MARGIN_PCT
FROM RAW_STAGE.STG_GLOBAL_SUPERSTORE
GROUP BY 1,2,3;