USE WAREHOUSE SUPERSTORE_WH;
USE DATABASE GLOBAL_SUPERSTORE_DW;
USE SCHEMA DW;

-- Row counts
SELECT COUNT(*) AS SALES_ROWS FROM FACT_SALES;
SELECT COUNT(*) AS SHIPPING_ROWS FROM FACT_SHIPPING;

-- Distinct orders check
SELECT COUNT(DISTINCT ORDER_ID) FROM FACT_SALES;

-- Shipping performance validation
SELECT MIN(DAYS_TO_SHIP), MAX(DAYS_TO_SHIP) FROM FACT_SHIPPING;
SELECT DISTINCT LATE_FLAG FROM FACT_SHIPPING;

-- Aggregated preview
SELECT * FROM FACT_CUSTOMER_MONTHLY LIMIT 10;
SELECT * FROM FACT_PRODUCT_MONTHLY LIMIT 10;

SHOW TABLES IN SCHEMA GLOBAL_SUPERSTORE_DW.TRANSFORM;