-- ======================================================
-- GLOBAL SUPERSTORE ETL PIPELINE – LOAD PHASE
-- ======================================================


USE WAREHOUSE SUPERSTORE_WH;
USE DATABASE GLOBAL_SUPERSTORE_DW;
USE SCHEMA TRANSFORM;



-- Create final DW schema if not exists
-- CREATE OR REPLACE SCHEMA DW;

-- ======================================================
-- 1️⃣ Load Dimension Tables
-- ======================================================

SHOW SCHEMAS IN DATABASE GLOBAL_SUPERSTORE_DW;

-- Date Dimension
CREATE OR REPLACE TABLE DW.DIM_DATE AS
SELECT * FROM TRANSFORM.DIM_DATE;

-- Customer Dimension
CREATE OR REPLACE TABLE DW.DIM_CUSTOMER AS
SELECT * FROM TRANSFORM.DIM_CUSTOMER;

-- Product Dimension
CREATE OR REPLACE TABLE DW.DIM_PRODUCT AS
SELECT * FROM TRANSFORM.DIM_PRODUCT;

-- Geography Dimension
CREATE OR REPLACE TABLE DW.DIM_GEOGRAPHY AS
SELECT * FROM TRANSFORM.DIM_GEOGRAPHY;

-- Shipping Dimension
CREATE OR REPLACE TABLE DW.DIM_SHIPPING AS
SELECT * FROM TRANSFORM.DIM_SHIPPING;

-- ======================================================
-- 2️⃣ Load Fact Tables
-- ======================================================

-- Fact Sales
CREATE OR REPLACE TABLE DW.FACT_SALES AS
SELECT * FROM TRANSFORM.FACT_SALES;

-- Fact Shipping
CREATE OR REPLACE TABLE DW.FACT_SHIPPING AS
SELECT * FROM TRANSFORM.FACT_SHIPPING;

-- Fact Customer Monthly
CREATE OR REPLACE TABLE DW.FACT_CUSTOMER_MONTHLY AS
SELECT * FROM TRANSFORM.FACT_CUSTOMER_MONTHLY;

-- Fact Product Monthly
CREATE OR REPLACE TABLE DW.FACT_PRODUCT_MONTHLY AS
SELECT * FROM TRANSFORM.FACT_PRODUCT_MONTHLY;

-- ======================================================
-- 3️⃣ Add Metadata Columns (Optional but Recommended)
-- ======================================================

-- ALTER TABLE DW.FACT_SALES ADD COLUMN LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP();
-- ALTER TABLE DW.FACT_SHIPPING ADD COLUMN LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP();
-- ALTER TABLE DW.FACT_CUSTOMERMONTHLY ADD COLUMN LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP();
-- ALTER TABLE DW.FACT_PRODUCTMONTHLY ADD COLUMN LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP();

-- ======================================================
-- 4️⃣ Validation (Counts Check)
-- ======================================================

SELECT 'DIM_CUSTOMER' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM DW.DIM_CUSTOMER
UNION ALL
SELECT 'DIM_PRODUCT', COUNT(*) FROM DW.DIM_PRODUCT
UNION ALL
SELECT 'DIM_GEOGRAPHY', COUNT(*) FROM DW.DIM_GEOGRAPHY
UNION ALL
SELECT 'FACT_PRODUCTMONTHLY', COUNT(*) FROM DW.FACT_PRODUCT_MONTHLY
UNION ALL
SELECT 'FACT_SALES', COUNT(*) FROM DW.FACT_SALES;



SELECT 'DIM_DATE' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM DW.DIM_DATE
UNION ALL
SELECT 'DIM_CUSTOMER', COUNT(*) FROM DW.DIM_CUSTOMER
UNION ALL
SELECT 'DIM_PRODUCT', COUNT(*) FROM DW.DIM_PRODUCT
UNION ALL
SELECT 'DIM_GEOGRAPHY', COUNT(*) FROM DW.DIM_GEOGRAPHY
UNION ALL
SELECT 'DIM_SHIPPING', COUNT(*) FROM DW.DIM_SHIPPING
UNION ALL
SELECT 'FACT_SALES', COUNT(*) FROM DW.FACT_SALES
UNION ALL
SELECT 'FACT_SHIPPING', COUNT(*) FROM DW.FACT_SHIPPING
UNION ALL
SELECT 'FACT_CUSTOMERMONTHLY', COUNT(*) FROM DW.FACT_CUSTOMER_MONTHLY
UNION ALL
SELECT 'FACT_PRODUCTMONTHLY', COUNT(*) FROM DW.FACT_PRODUCT_MONTHLY;










-- ======================================================
-- ✅ ETL Load Complete
-- ======================================================